name: phys142
channels:
    - conda-forge
dependencies:
    - python=3.10.10
    - jupyter_contrib_nbextensions==0.7.0
    - jupyter-book==0.15.1
    - numpy
    - ffmpeg
    - imagemagick
    - scikit-learn
    - matplotlib
    - tqdm
    - numba
    - cupy
    - pip
    - pip:
      - requests
      - ipywidgets
      - widgetsnbextension
