name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
      - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          channels: conda-forge
          activate-environment: phys142
          environment-file: environment.yml
          python-version: 3.10.10
          auto-activate-base: false

      # Check dependencies
      - name: Check Miniconda
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.6.1"

      - name: Add IJulia
        run: julia -e 'add IJulia'

      - name: Build the book
        shell: bash -l {0}
        run: |
          jupyter contrib nbextension install --user
          jupyter nbextension enable --py widgetsnbextension
          jupyter-book build .

      - name: Compile LaTeX
        uses: docker://xucheng/texlive-full:latest
        with:
          entrypoint: /bin/sh
          args: |
            -c "\
            cd syllabus && \
            latexmk"

      - name: Copy syllabus and homework for deployment
        run: |
          cp syllabus/syllabus.pdf _build/html/syllabus.pdf

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
